# Generated by Django 3.1.8 on 2023-03-06 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('instrument', models.CharField(help_text='Instrument name', max_length=7, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['instrument'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obsnum', models.CharField(help_text='Observation number, as a 3 digit string', max_length=3)),
                ('number_of_files', models.IntegerField(default=0, help_text='Number of files in the proposal')),
                ('obsstart', models.FloatField(default=0.0, help_text='Time of the beginning of the observation in MJD')),
                ('obsend', models.FloatField(default=0.0, help_text='Time of the end of the observation in MJD')),
                ('exptypes', models.CharField(default='', help_text='Comma-separated list of exposure types', max_length=100)),
            ],
            options={
                'ordering': ['-obsnum'],
            },
        ),
        migrations.CreateModel(
            name='RootFileInfo',
            fields=[
                ('instrument', models.CharField(help_text='Instrument name', max_length=7)),
                ('proposal', models.CharField(help_text='5-digit proposal ID string', max_length=5)),
                ('root_name', models.TextField(max_length=300, primary_key=True, serialize=False)),
                ('viewed', models.BooleanField(default=False)),
                ('filter', models.CharField(blank=True, default='', help_text='Instrument name', max_length=7, null=True)),
                ('aperture', models.CharField(blank=True, default='', help_text='Aperture', max_length=40, null=True)),
                ('detector', models.CharField(blank=True, default='', help_text='Detector', max_length=40, null=True)),
                ('read_patt_num', models.IntegerField(default=0, help_text='Read Pattern Number')),
                ('read_patt', models.CharField(blank=True, default='', help_text='Read Pattern', max_length=40, null=True)),
                ('grating', models.CharField(blank=True, default='', help_text='Grating', max_length=40, null=True)),
                ('subarray', models.CharField(blank=True, default='', help_text='Subarray', max_length=40, null=True)),
                ('pupil', models.CharField(blank=True, default='', help_text='Pupil', max_length=40, null=True)),
                ('exp_type', models.CharField(blank=True, default='', help_text='Exposure Type', max_length=40, null=True)),
                ('expstart', models.FloatField(default=0.0, help_text='Exposure Start Time')),
                ('obsnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwql.observation')),
            ],
            options={
                'ordering': ['-root_name'],
            },
        ),
        migrations.CreateModel(
            name='Anomalies',
            fields=[
                ('root_file_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jwql.rootfileinfo')),
                ('cosmic_ray_shower', models.BooleanField(default=False)),
                ('diffraction_spike', models.BooleanField(default=False)),
                ('excessive_saturation', models.BooleanField(default=False)),
                ('guidestar_failure', models.BooleanField(default=False)),
                ('persistence', models.BooleanField(default=False)),
                ('crosstalk', models.BooleanField(default=False)),
                ('data_transfer_error', models.BooleanField(default=False)),
                ('ghost', models.BooleanField(default=False)),
                ('snowball', models.BooleanField(default=False)),
                ('column_pull_up', models.BooleanField(default=False)),
                ('column_pull_down', models.BooleanField(default=False)),
                ('dominant_msa_leakage', models.BooleanField(default=False)),
                ('dragons_breath', models.BooleanField(default=False)),
                ('mrs_glow', models.BooleanField(default=False)),
                ('mrs_zipper', models.BooleanField(default=False)),
                ('internal_reflection', models.BooleanField(default=False)),
                ('optical_short', models.BooleanField(default=False)),
                ('row_pull_up', models.BooleanField(default=False)),
                ('row_pull_down', models.BooleanField(default=False)),
                ('lrs_contamination', models.BooleanField(default=False)),
                ('tree_rings', models.BooleanField(default=False)),
                ('scattered_light', models.BooleanField(default=False)),
                ('claws', models.BooleanField(default=False)),
                ('wisps', models.BooleanField(default=False)),
                ('tilt_event', models.BooleanField(default=False)),
                ('light_saber', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-root_file_info'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_id', models.CharField(help_text='5-digit proposal ID string', max_length=5)),
                ('thumbnail_path', models.CharField(default='', help_text='Path to the proposal thumbnail', max_length=100)),
                ('category', models.CharField(default='', help_text='Category Type', max_length=10)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwql.archive')),
            ],
            options={
                'ordering': ['-prop_id'],
                'unique_together': {('prop_id', 'archive')},
            },
        ),
        migrations.AddField(
            model_name='observation',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwql.proposal'),
        ),
    ]
