# Generated by Django 3.1.7 on 2022-09-09 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst', models.CharField(choices=[('FGS', 'FGS'), ('MIRI', 'MIRI'), ('NIRCam', 'NIRCam'), ('NIRISS', 'NIRISS'), ('NIRSpec', 'NIRSpec')], default=None, max_length=7, verbose_name='instrument')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('filepath', models.FilePathField(path='/user/lchambers/jwql/')),
            ],
            options={
                'verbose_name_plural': 'image data',
                'db_table': 'imagedata',
            },
        ),
        migrations.CreateModel(
            name='InstrumentFilterHandler',
            fields=[
                ('instrument', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThumbnailFilterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.PositiveIntegerField()),
                ('proposal', models.PositiveIntegerField()),
                ('root_name', models.CharField(max_length=300)),
                ('marked_viewed', models.BooleanField(default=False)),
                ('inst_handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwql.instrumentfilterhandler')),
            ],
        ),
    ]
