# Generated by Django 3.1.7 on 2022-09-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnailfilterinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='instrumentfilterhandler',
            name='instrument',
            field=models.TextField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thumbnailfilterinfo',
            name='root_name',
            field=models.TextField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
