# Generated by Django 3.1.7 on 2022-09-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0003_auto_20220921_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnailfilterinfo',
            name='obsnum',
            field=models.CharField(default=11, help_text='Observation number, as a 3 digit string', max_length=3),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RootFileInfo',
            fields=[
                ('instrument', models.CharField(help_text='Instrument name', max_length=7)),
                ('proposal', models.CharField(help_text='5-digit proposal ID string', max_length=5)),
                ('root_name', models.TextField(max_length=300, primary_key=True, serialize=False)),
                ('viewed', models.BooleanField(default=False)),
                ('obsnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwql.observation')),
            ],
            options={
                'ordering': ['-root_name'],
            },
        ),
    ]
