# Generated by Django 3.1.7 on 2023-02-14 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0005_auto_20220922_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalies',
            fields=[
                ('root_file_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jwql.rootfileinfo')),
                ('cosmic_ray_shower', models.BooleanField(default=False)),
                ('diffraction_spike', models.BooleanField(default=False)),
                ('excessive_saturation', models.BooleanField(default=False)),
                ('guidestar_failure', models.BooleanField(default=False)),
                ('persistence', models.BooleanField(default=False)),
                ('crosstalk', models.BooleanField(default=False)),
                ('data_transfer_error', models.BooleanField(default=False)),
                ('ghost', models.BooleanField(default=False)),
                ('snowball', models.BooleanField(default=False)),
                ('column_pull_up', models.BooleanField(default=False)),
                ('column_pull_down', models.BooleanField(default=False)),
                ('dominant_msa_leakage', models.BooleanField(default=False)),
                ('dragons_breath', models.BooleanField(default=False)),
                ('mrs_glow', models.BooleanField(default=False)),
                ('mrs_zipper', models.BooleanField(default=False)),
                ('internal_reflection', models.BooleanField(default=False)),
                ('optical_short', models.BooleanField(default=False)),
                ('row_pull_up', models.BooleanField(default=False)),
                ('row_pull_down', models.BooleanField(default=False)),
                ('lrs_contamination', models.BooleanField(default=False)),
                ('tree_rings', models.BooleanField(default=False)),
                ('scattered_light', models.BooleanField(default=False)),
                ('claws', models.BooleanField(default=False)),
                ('wisps', models.BooleanField(default=False)),
                ('tilt_event', models.BooleanField(default=False)),
                ('light_saber', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-root_file_info'],
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='cat_type',
            field=models.CharField(default='', help_text='Category Type', max_length=10),
        ),
        migrations.AddField(
            model_name='rootfileinfo',
            name='aperature',
            field=models.CharField(default='', help_text='Aperature', max_length=40),
        ),
        migrations.AddField(
            model_name='rootfileinfo',
            name='detector',
            field=models.CharField(default='', help_text='Detector', max_length=40),
        ),
        migrations.AddField(
            model_name='rootfileinfo',
            name='filter',
            field=models.CharField(default='', help_text='Instrument name', max_length=7),
        ),
        migrations.AddField(
            model_name='rootfileinfo',
            name='grating',
            field=models.CharField(default='', help_text='Grating', max_length=40),
        ),
        migrations.AddField(
            model_name='rootfileinfo',
            name='pupil',
            field=models.CharField(default='', help_text='Pupil', max_length=40),
        ),
        migrations.AddField(
            model_name='rootfileinfo',
            name='read_patt',
            field=models.CharField(default='', help_text='Read Pattern', max_length=40),
        ),
        migrations.AddField(
            model_name='rootfileinfo',
            name='read_patt_num',
            field=models.IntegerField(default=0, help_text='Read Pattern Number'),
        ),
        migrations.AddField(
            model_name='rootfileinfo',
            name='subarray',
            field=models.CharField(default='', help_text='Subarray', max_length=40),
        ),
    ]
