# Generated by Django 3.1.7 on 2023-02-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0006_auto_20230214_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rootfileinfo',
            name='aperature',
        ),
        migrations.AddField(
            model_name='rootfileinfo',
            name='aperture',
            field=models.CharField(default='', help_text='Aperture', max_length=40),
        ),
    ]
