# Generated by Django 3.1.7 on 2023-02-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0007_auto_20230222_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootfileinfo',
            name='exp_type',
            field=models.CharField(default='', help_text='Exposure Type', max_length=40),
        ),
    ]
