# Generated by Django 3.1.7 on 2023-03-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0008_rootfileinfo_exp_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='cat_type',
            new_name='category',
        ),
        migrations.AddField(
            model_name='rootfileinfo',
            name='expstart',
            field=models.FloatField(default=0.0, help_text='Exposure Start Time'),
        ),
        migrations.AlterField(
            model_name='rootfileinfo',
            name='aperture',
            field=models.CharField(blank=True, default='', help_text='Aperture', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='rootfileinfo',
            name='detector',
            field=models.CharField(blank=True, default='', help_text='Detector', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='rootfileinfo',
            name='exp_type',
            field=models.CharField(blank=True, default='', help_text='Exposure Type', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='rootfileinfo',
            name='filter',
            field=models.CharField(blank=True, default='', help_text='Instrument name', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='rootfileinfo',
            name='grating',
            field=models.CharField(blank=True, default='', help_text='Grating', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='rootfileinfo',
            name='pupil',
            field=models.CharField(blank=True, default='', help_text='Pupil', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='rootfileinfo',
            name='read_patt',
            field=models.CharField(blank=True, default='', help_text='Read Pattern', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='rootfileinfo',
            name='subarray',
            field=models.CharField(blank=True, default='', help_text='Subarray', max_length=40, null=True),
        ),
    ]
