# Generated by Django 3.1.7 on 2023-03-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0009_auto_20230303_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalies',
            name='flag_date',
            field=models.DateTimeField(blank=True, help_text='flag date', null=True),
        ),
        migrations.AddField(
            model_name='anomalies',
            name='user',
            field=models.CharField(blank=True, default='', help_text='user', max_length=50, null=True),
        ),
    ]
