# Generated by Django 4.1.7 on 2024-01-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0011_rename_snowball_anomalies_unusual_snowballs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomalies',
            old_name='dominant_msa_leakage',
            new_name='noticeable_msa_leakage',
        ),
    ]
