# Generated by Django 4.1.7 on 2024-01-12 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0012_rename_dominant_msa_leakage_anomalies_noticeable_msa_leakage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomalies',
            old_name='optical_short',
            new_name='new_short',
        ),
    ]
