# Generated by Django 4.1.7 on 2024-01-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0013_rename_optical_short_anomalies_new_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalies',
            name='unusual_cosmic_rays',
            field=models.BooleanField(default=False),
        ),
    ]
