# Generated by Django 4.1.7 on 2024-01-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0014_anomalies_unusual_cosmic_rays'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalies',
            name='needs_discussion',
            field=models.BooleanField(default=False),
        ),
    ]
