# Generated by Django 4.1.7 on 2024-01-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0015_anomalies_needs_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalies',
            name='bright_object_not_a_short',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anomalies',
            name='monitored_short',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anomalies',
            name='subsequently_masked_short',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anomalies',
            name='transient_short',
            field=models.BooleanField(default=False),
        ),
    ]
