# Generated by Django 4.2.5 on 2024-02-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0017_nirspecreadnoisestats_nirspecreadnoisequeryhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nircamclawstats',
            name='doy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nircamclawstats',
            name='total_bkg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
