# Generated by Django 4.2.5 on 2024-02-20 20:04

import django.contrib.postgres.fields
from django.db import migrations, models
import sys


def db_select(apps, schema_editor):
    if schema_editor.connection.alias == "default":
        # Anything that's not for the monitors tables
        return
    else:
        migrations.AddField(
            model_name='nircam_claw_stats',
            name='doy',
            field=models.FloatField(blank=True, null=True),
        )
        migrations.AddField(
            model_name='nircam_claw_stats',
            name='total_bkg',
            field=models.FloatField(blank=True, null=True),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0018_centralstorage_fgsanomaly_filesystemcharacteristics_and_more'),
    ]

    operations = [
        migrations.RunPython(db_select),
    ]
