# Generated by Django 4.1.7 on 2024-03-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0018_nircamclawstats_doy_nircamclawstats_total_bkg'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalies',
            name='brad_delete_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nircamclawstats',
            name='brad_delete_monitor',
            field=models.BooleanField(default=False),
        ),
    ]
