# Generated by Django 4.2.5 on 2024-02-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0019_add_claw_table_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='nircamclawstats',
            name='doy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nircamclawstats',
            name='total_bkg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
