# Generated by Django 5.0.7 on 2024-07-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0024_nirspecmsatastats_nirspecwatastats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootfileinfo',
            name='comment',
            field=models.TextField(blank=True, default='No Comments Yet', help_text='Anomaly Comment Field', null=True),
        ),
    ]
