# Generated by Django 5.0.7 on 2024-07-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0024_nirspecmsatastats_nirspecwatastats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootfileinfo',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Anomaly Comment Field'),
        ),
        migrations.AddField(
            model_name='rootfileinfo',
            name='exp_comment',
            field=models.TextField(blank=True, default='', help_text='Anomaly Comment Field'),
        ),
    ]
