# Generated by Django 5.0.7 on 2024-08-30 15:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0025_rootfileinfo_comment_rootfileinfo_exp_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='amplifier',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='aperture',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='double_gauss_amplitude1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='double_gauss_amplitude2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='double_gauss_chisq',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='double_gauss_peak1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='double_gauss_peak2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='double_gauss_width1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='double_gauss_width2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='gauss_amplitude',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='gauss_chisq',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='gauss_peak',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='gauss_width',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='hist_amplitudes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='hist_dark_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='mean',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='mean_dark_image_file',
            field=models.CharField(default='empty', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='readpattern',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='source file names', max_length=1000), blank=True, default='empty', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='stdev',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='fgsdarkpixelstats',
            name='baseline_file',
            field=models.CharField(default='empty', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fgsdarkpixelstats',
            name='detector',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='fgsdarkpixelstats',
            name='mean_dark_image_file',
            field=models.CharField(default='empty', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fgsdarkpixelstats',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='source file names', max_length=1000), blank=True, default='empty', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='fgsdarkpixelstats',
            name='type',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='fgsdarkqueryhistory',
            name='aperture',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='fgsdarkqueryhistory',
            name='files_found',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fgsdarkqueryhistory',
            name='instrument',
            field=models.CharField(blank=True, default='empty', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='fgsdarkqueryhistory',
            name='readpattern',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='amplifier',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='aperture',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='double_gauss_amplitude1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='double_gauss_amplitude2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='double_gauss_chisq',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='double_gauss_peak1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='double_gauss_peak2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='double_gauss_width1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='double_gauss_width2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='gauss_amplitude',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='gauss_chisq',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='gauss_peak',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='gauss_width',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='hist_amplitudes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='hist_dark_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='mean',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='mean_dark_image_file',
            field=models.CharField(default='empty', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='readpattern',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='source file names', max_length=1000), blank=True, default='empty', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='stdev',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='miridarkpixelstats',
            name='baseline_file',
            field=models.CharField(default='empty', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='miridarkpixelstats',
            name='detector',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='miridarkpixelstats',
            name='mean_dark_image_file',
            field=models.CharField(default='empty', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='miridarkpixelstats',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='source file names', max_length=1000), blank=True, default='empty', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='miridarkpixelstats',
            name='type',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='miridarkqueryhistory',
            name='aperture',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='miridarkqueryhistory',
            name='files_found',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='miridarkqueryhistory',
            name='instrument',
            field=models.CharField(blank=True, default='empty', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='miridarkqueryhistory',
            name='readpattern',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='amplifier',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='aperture',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='double_gauss_amplitude1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='double_gauss_amplitude2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='double_gauss_chisq',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='double_gauss_peak1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='double_gauss_peak2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='double_gauss_width1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='double_gauss_width2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='gauss_amplitude',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='gauss_chisq',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='gauss_peak',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='gauss_width',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='hist_amplitudes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='hist_dark_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='mean',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='mean_dark_image_file',
            field=models.CharField(default='empty', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='readpattern',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='source file names', max_length=1000), blank=True, default='empty', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='stdev',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='nircamdarkpixelstats',
            name='baseline_file',
            field=models.CharField(default='empty', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nircamdarkpixelstats',
            name='detector',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nircamdarkpixelstats',
            name='mean_dark_image_file',
            field=models.CharField(default='empty', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nircamdarkpixelstats',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='source file names', max_length=1000), blank=True, default='empty', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='nircamdarkpixelstats',
            name='type',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nircamdarkqueryhistory',
            name='aperture',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nircamdarkqueryhistory',
            name='files_found',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='nircamdarkqueryhistory',
            name='instrument',
            field=models.CharField(blank=True, default='empty', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='nircamdarkqueryhistory',
            name='readpattern',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='amplifier',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='aperture',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='double_gauss_amplitude1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='double_gauss_amplitude2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='double_gauss_chisq',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='double_gauss_peak1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='double_gauss_peak2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='double_gauss_width1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='double_gauss_width2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='gauss_amplitude',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='gauss_chisq',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='gauss_peak',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='gauss_width',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='hist_amplitudes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='hist_dark_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='mean',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='mean_dark_image_file',
            field=models.CharField(default='empty', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='readpattern',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='source file names', max_length=1000), blank=True, default='empty', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='stdev',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='nirissdarkpixelstats',
            name='baseline_file',
            field=models.CharField(default='empty', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nirissdarkpixelstats',
            name='detector',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nirissdarkpixelstats',
            name='mean_dark_image_file',
            field=models.CharField(default='empty', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nirissdarkpixelstats',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='source file names', max_length=1000), blank=True, default='empty', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='nirissdarkpixelstats',
            name='type',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nirissdarkqueryhistory',
            name='aperture',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nirissdarkqueryhistory',
            name='files_found',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='nirissdarkqueryhistory',
            name='instrument',
            field=models.CharField(blank=True, default='empty', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='nirissdarkqueryhistory',
            name='readpattern',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='amplifier',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='aperture',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='double_gauss_amplitude1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='double_gauss_amplitude2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='double_gauss_chisq',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='double_gauss_peak1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='double_gauss_peak2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='double_gauss_width1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='double_gauss_width2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='gauss_amplitude',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='gauss_chisq',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='gauss_peak',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='gauss_width',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='hist_amplitudes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='hist_dark_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='mean',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='mean_dark_image_file',
            field=models.CharField(default='empty', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='readpattern',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='source file names', max_length=1000), blank=True, default='empty', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='stdev',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='nirspecdarkpixelstats',
            name='baseline_file',
            field=models.CharField(default='empty', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nirspecdarkpixelstats',
            name='detector',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nirspecdarkpixelstats',
            name='mean_dark_image_file',
            field=models.CharField(default='empty', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nirspecdarkpixelstats',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='source file names', max_length=1000), blank=True, default='empty', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='nirspecdarkpixelstats',
            name='type',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nirspecdarkqueryhistory',
            name='aperture',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='nirspecdarkqueryhistory',
            name='files_found',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='nirspecdarkqueryhistory',
            name='instrument',
            field=models.CharField(blank=True, default='empty', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='nirspecdarkqueryhistory',
            name='readpattern',
            field=models.CharField(blank=True, default='empty', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='rootfileinfo',
            name='exp_comment',
            field=models.TextField(blank=True, default='', help_text='Anomaly Comment Field'),
        ),
    ]
