# Generated by Django 5.1 on 2024-11-12 19:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwql', '0026_alter_fgsdarkdarkcurrent_amplifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fgsbadpixelstats',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='empty', help_text='source file names', max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='fgsdarkdarkcurrent',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='empty', help_text='source file names', max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='fgsdarkpixelstats',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='empty', help_text='source file names', max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='miribadpixelstats',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='empty', help_text='source file names', max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='miridarkdarkcurrent',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='empty', help_text='source file names', max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='miridarkpixelstats',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='empty', help_text='source file names', max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='nircambadpixelstats',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='empty', help_text='source file names', max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='nircamdarkdarkcurrent',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='empty', help_text='source file names', max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='nircamdarkpixelstats',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='empty', help_text='source file names', max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='nirissbadpixelstats',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='empty', help_text='source file names', max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='nirissdarkdarkcurrent',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='empty', help_text='source file names', max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='nirissdarkpixelstats',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='empty', help_text='source file names', max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='nirspecbadpixelstats',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='empty', help_text='source file names', max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='nirspecdarkdarkcurrent',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='empty', help_text='source file names', max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='nirspecdarkpixelstats',
            name='source_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='empty', help_text='source file names', max_length=1000), blank=True, null=True, size=None),
        ),
    ]
