version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: monthly
      time: "03:00"

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: monthly
      time: "03:00"
    open-pull-requests-limit: 10
