# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# Required
version: 2
# Set the version of Python and other tools you might need
# Explicit sqlalchemy install using post_install in order to get around the RTD
# command pip install --upgrade --upgrade-strategy eager
# This command upgrades all packages listed in rtd_reuirements.txt. This was causing
# a problem when upgrading to sqlalchemy >=2.0, which has large changes from versions
# <2.0, and was causing jwql to crash.
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install sqlalchemy==1.4.46

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py
   fail_on_warning: false
# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf
# Optionally declare the Python requirements required to build your docs
python:
   install:
      - requirements: rtd_requirements.txt
      - method: pip
        path: .
