codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "0...75"

  status:
    project: off
    patch: off
    changes: off

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: no

ignore:
  - "jwql/database/"
  - "jwql/instrument_monitors/miri_monitors/data_trending/plots/"
  - "jwql/instrument_monitors/nirspec_monitors/data_trending/plots/"
  - "jwql/website/"
  - "*__init__.py*"
  - "**/*.html"
  - "**/*.js"
  - "**/*.css"
