# Generated by Django 2.0.1 on 2018-02-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst', models.CharField(max_length=200)),
                ('pub_dat', models.DateTimeField(verbose_name='date published')),
                ('filename', models.FileField(upload_to=models.CharField(max_length=200))),
            ],
        ),
    ]
