# Generated by Django 2.0.1 on 2018-02-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots_example', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagedata',
            old_name='pub_dat',
            new_name='pub_date',
        ),
    ]
