# Generated by Django 2.0.1 on 2018-02-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots_example', '0002_auto_20180202_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='filename',
            field=models.FileField(upload_to=models.CharField(choices=[('FGS', 'FGS'), ('MIRI', 'MIRI'), ('NIRCam', 'NIRCam'), ('NIRISS', 'NIRISS'), ('NIRSpec', 'NIRSpec')], default=None, max_length=6)),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='inst',
            field=models.CharField(choices=[('FGS', 'FGS'), ('MIRI', 'MIRI'), ('NIRCam', 'NIRCam'), ('NIRISS', 'NIRISS'), ('NIRSpec', 'NIRSpec')], default=None, max_length=6),
        ),
    ]
