# Generated by Django 2.0.1 on 2018-02-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots_example', '0003_auto_20180202_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='filename',
            field=models.FileField(upload_to='<django.db.models.fields.CharField>'),
        ),
    ]
