# Generated by Django 2.0.1 on 2018-02-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots_example', '0004_auto_20180202_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='filename',
            field=models.FileField(upload_to=''),
        ),
    ]
