# Generated by Django 2.0.1 on 2018-02-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots_example', '0005_auto_20180206_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedata',
            name='filename',
        ),
        migrations.AddField(
            model_name='imagedata',
            name='filepath',
            field=models.FilePathField(default='/user/lchambers/jwql/', path='/user/lchambers/jwql/'),
            preserve_default=False,
        ),
    ]
