# Generated by Django 2.0.1 on 2018-02-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots_example', '0007_auto_20180220_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationsWebtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_id', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50, unique=True)),
                ('observer', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=100)),
                ('filetype', models.CharField(max_length=50)),
                ('prop_title', models.CharField(max_length=100)),
                ('target_name', models.CharField(max_length=50)),
                ('instrument', models.CharField(max_length=50)),
                ('exposure_type', models.CharField(max_length=50)),
                ('aperture_name', models.CharField(max_length=50)),
            ],
            options={
                'managed': False,
                'db_table': 'observations_webtest',
            },
        ),
        migrations.AlterModelTable(
            name='imagedata',
            table='imagedata',
        ),
    ]
