"""utils_f.py

    Contains all utils/variables/definitions/settings for dashboard.py (coherently)

Authors
-------

    - [AIRBUS] Leo Stumpf

Use
---
    -

Dependencies
------------

    The file nirspec_database.db in the directory jwql/jwql/database/ must be populated.

References
----------
    The code was developed in reference to the information provided in:
    ‘JWQL_NIRSpec_Inputs_V8.xlsx’

Notes
-----

    For further information please contact Brian O'Sullivan
"""
import datetime
from bokeh.models import DatetimeTickFormatter

# Defines Layout of the Legend of all plots
plot_x_axis_format = DatetimeTickFormatter(
    hours=["%Y-%m-%d ,%H:%M:%S.%f"],
    days=["%Y-%m-%d, %H:%M"],
    months=["%Y-%m-%d"],
    years=["%Y-%m-%d"],
)

# Time Delta function it is used to only display a certain timeframe of e.g. the last 120 days
def time_delta(endtime):
    timeDeltaEnd = endtime.datetime
    timeDelta = [timeDeltaEnd - datetime.timedelta(days=120), timeDeltaEnd]
    return timeDelta

# Tab Description
description_caa = [
    [['CAA Lamp Voltages'],['INRSH_LAMP_SEL','INRSI_C_CAA_VOLTAGE'],['Lamp Voltage for each CAA Lamp']],
    [['CAA Lamp Currents'],['INRSH_LAMP_SEL','INRSI_C_CAA_CURRENT'],['Lamp Currents for each CAA Lamp']],
]

# Tab Description
description_fpe_fpa = [
    [['ASIC (1,2) Voltages'],  ['IGDP_NRSD_ALG_A(1,2)_VDDA',
                                'IGDP_NRSD_ALG_A(1,2)GND4VDA',
                                'IGDP_NRSD_ALG_A(1,2)GND5VRF',
                                'INRSD_ALG_A(1,2)_VDD3P3',
                                'INRSD_ALG_A(1,2)_VDD',
                                'INRSD_ALG_A(1,2)_REF',
                                'INRSD_A(1,2)_DSUB_V',
                                'INRSD_A(1,2)_VRESET_V',
                                'INRSD_A(1,2)_CELLDRN_V',
                                'INRSD_A(1,2)_DRAIN_V',
                                'INRSD_A(1,2)_VBIASGATE_V',
                                'INRSD_A(1,2)_VBIASPWR_V',],   ['ASIC (1,2) VDDA Voltage',
                                                                'ASIC (1,2) VDDA/Ground Voltage',
                                                                'ASIC (1,2) Ref/Ground Voltage',
                                                                'ASIC (1,2) VDD 3.3 Supply Voltage',
                                                                'ASIC (1,2) VDD Voltage',
                                                                'ASIC (1,2) Reference Voltage',
                                                                'ASIC (1,2) Dsub Voltage',
                                                                'ASIC (1,2) Reset Voltage',
                                                                'ASIC (1,2) Cell Drain Voltage',
                                                                'ASIC (1,2) Drain Voltage',
                                                                'ASIC (1,2) Bias Gate Voltage',
                                                                'ASIC (1,2) Bias Power Voltage',]],
    [['ASIC (1,2) Currents'],
     ['IGDP_NRSD_ALG_A(1,2)_VDD_C',
        'IGDP_NRSD_ALG_A(1,2)VDAP12C',
        'IGDP_NRSD_ALG_A(1,2)VDAN12C',
        'INRSD_A(1,2)_VDDA_I'],
     ['ASIC (1,2) VDD Current',
        'ASIC (1,2) VDDA +12V Current',
        'ASIC (1,2) VDDA -12V Current',
        'ASIC (1,2) VDDA Current', ]],
]

# Tab Description
description_msa_mce = [
    [['MCE Board 1 (AIC) Voltages'],
     ['INRSM_MCE_AIC_1R5_V','INRSM_MCE_AIC_3R3_V',
      'INRSM_MCE_AIC_5_V','INRSM_MCE_AIC_P12_V','INRSM_MCE_AIC_N12_V'],
     ['MCE AIC +1.5V Voltage','MCE AIC +3.3V Voltage',
      'MCE AIC +5V Voltage','MCE AIC +12V Voltage','MCE AIC -12V Voltage']],
    [['MCE Board 1 (AIC) Currents'],
     ['INRSM_MCE_AIC_3R3_I','INRSM_MCE_AIC_5_I',
      'INRSM_MCE_AIC_P12_I','INRSM_MCE_AIC_N12_I'],
     ['MCE AIC Board +3.3V Current','MCE AIC Board +5V Current',
      'MCE AIC Board +12V Current','MCE AIC Board -12V Current']],
    [['MCE Board 2 (MDAC) Voltages'],['INRSM_MCE_MDAC_1R5_V',
                                      'INRSM_MCE_MDAC_3R3_V',
                                      'INRSM_MCE_MDAC_5_V',
                                      'INRSM_MCE_MDAC_P12_V',
                                      'INRSM_MCE_MDAC_N12_V',],['MCE MDAC +1.5V Voltage',
                                                                'MCE MDAC +3.3V Voltage',
                                                                'MCE MDAC +5V Voltage',
                                                                'MCE MDAC +12V Voltage',
                                                                'MCE MDAC -12V Voltage']],
    [['MCE Board 2 (MDAC) Currents'], ['INRSM_MCE_MDAC_3R3_I',
                                       'INRSM_MCE_MDAC_5_I',
                                       'INRSM_MCE_MDAC_P12_I',
                                       'INRSM_MCE_MDAC_N12_I'], ['MCE MDAC Board +3.3V Current',
                                                                 'MCE MDAC Board +5V Current',
                                                                 'MCE MDAC Board +12V Current',
                                                                 'MCE MDAC Board -12V Current']],
    [['QUAD (1-4)'], ['INRSM_MSA_Q(1-4)_365VDD',
                      'INRSM_MSA_Q(1-4)_365VPP',
                      'INRSM_MSA_Q(1-4)_171VPP',
                      'IGDPM_MSA_Q(1-4)_365IDD',
                      'IGDPM_MSA_Q(1-4)_365IPP',
                      'IGDPM_MSA_Q(1-4)_171RTN'], ['MSA Quad (1-4) Vdd 365 Voltage',
                                                   'MSA Quad (1-4) Vpp 365 Voltage',
                                                   'MSA Quad (1-4) Vpp 171 Voltage',
                                                   'MSA Quad (1-4) Vdd 365 Current',
                                                   'MSA Quad (1-4) Vpp 365 Current',
                                                   'MSA Quad (1-4) Return 171 Current']],
]

# Tab Description
description_power = [
    [['ICE Power Parameters'],['GP_ZPSVOLT (missing)',
                               'SE_ZINRSICEA',
                               'INRSH_HK_P15V',
                               'INRSH_HK_N15V',
                               'INRSH_HK_VMOTOR',
                               'INRSH_HK_P5V',
                               'INRSH_HK_2P5V',
                               'INRSH_HK_ADCTGAIN',
                               'INRSH_HK_ADCTOFFSET',
                               'INRSH_OA_VREFOFF',
                               'INRSH_OA_VREF',],['',
                                                  'ICE Input Voltage',
                                                  'ICE Input Current (A side)',
                                                  'ICE +15V Voltage',
                                                  'ICE -15V Voltage',
                                                  'ICE Motor Voltage',
                                                  'ICE +5V FPGA Voltage',
                                                  'ICE +2V5 FPGA Voltage',
                                                  'ICE ADC TM Chain Gain for Calibration',
                                                  'ICE ADC TM Chain Offset for Calibration',
                                                  '']],
    [['MCE Power Parameters'],['GP_ZPSVOLT (missing)',
                               'SE_ZINRSMCEA'],['ICE Input Voltage',
                                                'MCE Input Current (A side)']],
    [['FPE Power Parameters'],['GP_ZPSVOLT (missing)',
                               'SE_ZINRSFPEA',
                               'INRSD_ALG_ACC_P12C',
                               'INRSD_ALG_ACC_N12C',
                               'INRSD_ALG_ACC_3D3_1D5_C',
                               'INRSD_ALG_CHASSIS'],['ICE Input Voltage',
                                                     'MCE Input Current (A side)',
                                                     'ACC +12V Current',
                                                     'ACC -12V Current',
                                                     'ACC 3.3/1.5 Supply Current',
                                                     'Chassis Voltage']],
]

# Tab Description
description_tab = [
    [['IRSU monitored Temperatures'],
                                    ['SI_GZCTS75A',
                                     'SI_GZCTS68A',
                                     'SI_GZCTS81A',
                                     'SI_GZCTS80A',
                                     'SI_GZCTS76A',
                                     'SI_GZCTS79A',
                                     'SI_GZCTS77A',
                                     'SI_GZCTS78A',
                                     'SI_GZCTS69A'],
                                                                        ['CAA IRSU Temperature'
                                                                         'CAM IRSU Temperature',
                                                                         'COM1 Nominal IRSU Temperature',
                                                                         'COM1 Redundant IRSU Temperature',
                                                                         'FWA IRSU Temperature',
                                                                         'GWA IRSU Temperature',
                                                                         'Thermal Strap Nominal IRSU Temperature',
                                                                         'Thermal Strap Redundant IRSU Temperature',
                                                                         'MSA Nominal IRSU Temperature',
                                                                         'MSA Redundant IRSU Temperature',]],
    [['FPE Temperatures'],
                                    ['IGDP_NRSI_C_CAM_TEMP',
                                     'IGDP_NRSI_C_COL_TEMP',
                                     'IGDP_NRSI_C_COM1_TEMP',
                                     'IGDP_NRSI_C_FOR_TEMP',
                                     'IGDP_NRSI_C_IFU_TEMP',
                                     'IGDP_NRSI_C_BP1_TEMP',
                                     'IGDP_NRSI_C_BP2_TEMP',
                                     'IGDP_NRSI_C_BP3_TEMP',
                                     'IGDP_NRSI_C_BP4_TEMP',
                                     'IGDP_NRSI_C_RMA_TEMP'],
                                                                        ['OA CAM Temperature',
                                                                         'OA COL Temperature',
                                                                         'OA COM1 Temperature',
                                                                         'OA FOR Temperature',
                                                                         'OA IFU Temperature',
                                                                         'OA BP1 Temperature',
                                                                         'OA BP2 Temperature',
                                                                         'OA BP3 Temperature',
                                                                         'OA BP4 Temperature',
                                                                         'OA RMA Temperature']],
    [['Box Temperatures'],
                                    ['IGDP_NRSD_ALG_TEMP',
                                     'INRSH_HK_TEMP1',
                                     'INRSH_HK_TEMP2'],
                                                                        ['',
                                                                         'ICE Internal Temperature 1',
                                                                         'ICE Internal Temperature 2']],

    [['MCE internal Temperatures'],
                                    ['INRSM_MCE_PCA_TMP1',
                                     'INRSM_MCE_PCA_TMP2',
                                     'INRSM_MCE_AIC_TMP_FPGA',
                                     'INRSM_MCE_AIC_TMP_ADC',
                                     'INRSM_MCE_AIC_TMP_VREG',
                                     'INRSM_MCE_MDAC_TMP_FPGA',
                                     'INRSM_MCE_MDAC_TMP_OSC',
                                     'INRSM_MCE_MDAC_TMP_BRD',
                                     'INRSM_MCE_MDAC_TMP_PHA',
                                     'INRSM_MCE_MDAC_TMP_PHB',],
                                                                        ['MCE PCA Board Temperature 1',
                                                                         'MCE PCA Board Temperature 2',
                                                                         'MCE AIC Board FPGA Temperature',
                                                                         'MCE AIC Board Analog/Digital Converter Temperature',
                                                                         'MCE AIC Board Voltage Regulator Temperature',
                                                                         'MCE MDAC Board FPGA Temperature',
                                                                         'MCE MDAC Board Oscillator Temperature',
                                                                         'MCE MDAC Board Temperature',
                                                                         'MCE MDAC Board Phase A PA10 Temperature',
                                                                         'MCE MDAC Board Phase B PA10 Temperature']],
    [['MSA Temperatures'],
                                    ['INRSM_Q1_TMP_A',
                                     'INRSM_Q2_TMP_A',
                                     'INRSM_Q3_TMP_A',
                                     'INRSM_Q4_TMP_A',
                                     'INRSM_MECH_MTR_TMP_A',
                                     'INRSM_LL_MTR_TMP_A',
                                     'INRSM_MSA_TMP_A'],
                                                                        ['MSA Quad 1 Temperature',
                                                                         'MSA Quad 2 Temperature',
                                                                         'MSA Quad 3 Temperature',
                                                                         'MSA Quad 4 Temperature',
                                                                         'MSA Magnetic Arm Motor Temperature',
                                                                         'MSA Launch Lock Motor Temperature',
                                                                         'MSA Frame Temperature']],
    [['FPA Temperatures'],
                                    ['',
                                     'IGDP_NRSD_ALG_FPA_TEMP',
                                     'IGDP_NRSD_ALG_A1_TEMP',
                                     'IGDP_NRSD_ALG_A2_TEMP'],
                                                                        ['FPE Temperature',
                                                                         'FPA Temperature',
                                                                         'ASIC 1 Temperature',
                                                                         'ASIC 2 Temperature']],

    [['Heat Strap Temperatures (Trim Heaters)'],
                                    ['SI_GZCTS74A',
                                     'SI_GZCTS67A'],
                                                                        ['FPA TH-Strap A Temperature from IRSU A',
                                                                         'FPA TH-Strap B Temperature from IRSU A']],

    [['CAA Lamps / FWA,GWA'],
                                    ['IGDP_NRSI_C_CAAL1_TEMP',
                                     'IGDP_NRSI_C_CAAL2_TEMP',
                                     'IGDP_NRSI_C_CAAL3_TEMP',
                                     'IGDP_NRSI_C_CAAL4_TEMP',
                                     'IGDP_NRSI_C_FWA_TEMP',
                                     'IGDP_NRSI_C_GWA_TEMP'],
                                                                        ['CAA Temperature LINE1',
                                                                         'CAA Temperature LINE2',
                                                                         'CAA Temperature LINE3',
                                                                         'CAA Temperature LINE4',
                                                                         'FWA Temperature Sensor Value',
                                                                         'GWA Temperature Sensor Value']],
]

# Tab Description
description_volt = [
    [['Ref Voltages'],
                                    ['INRSH_FWA_MOTOR_VREF',
                                     'INRSH_GWA_MOTOR_VREF',
                                     'INRSH_OA_VREF'],
                                                                        ['FWA Motor Reference Voltage for Calibration',
                                                                         'GWA Motor Reference Voltage for Calibration',
                                                                         'OA/RMA Reference Voltage for TM Calibration']],
    [['ADCMGAIN'],
                                    ['INRSH_FWA_ADCMGAIN',
                                     'INRSH_GWA_ADCMGAIN',
                                     'INRSH_RMA_ADCMGAIN'],
                                                                        ['FWA ADC Motor Chain Gain for Calibration',
                                                                         'GWA ADC Motor Chain Gain for Calibration',
                                                                         'RMA ADC Motor Chain Gain for Calibration']],
    [['OFFSET'],
                                    ['INRSH_FWA_ADCMOFFSET',
                                     'INRSH_GWA_ADCMOFFSET',
                                     'INRSH_OA_VREFOFF',
                                     'INRSH_RMA_ADCMOFFSET'],
                                                                        ['FWA ADC Motor Chain Offset for Calibration',
                                                                         'GWA ADC Motor Chain Offset for Calibration'
                                                                         'CAA Reference Voltage Offset for TM Calibration',
                                                                         'RMA ADC Motor Chain Offset for Calibration']],
]

# Tab Description
description_wheel = [
    [['Filterwheel'],
                                    ['INRSI_FWA_MECH_POS',
                                     'INRSI_C_FWA_POSITION'],
                                                                        ['Position Sensor Value',
                                                                         'Current Position']],
    [['Gratingwheel X'],
                                    ['INRSI_GWA_MECH_POS',
                                     'INRSI_C_GWA_X_POSITION'],
                                                                        ['Position X Sensor Value',
                                                                         'Current Position']],
    [['Gratingwheel Y'],
                                    ['INRSI_GWA_MECH_POS',
                                     'INRSI_C_GWA_Y_POSITION'],
                                                                        ['Position Y Sensor Value',
                                                                         'Current Position']],
]


# List of anomalys to be displayed on a certain page
list_voltage = [
    'INRSH_FWA_MOTOR_VREF',
    'INRSH_GWA_MOTOR_VREF',
    'INRSH_OA_VREF',
    'INRSH_FWA_ADCMGAIN',
    'INRSH_GWA_ADCMGAIN',
    'INRSH_RMA_ADCMGAIN',
    'INRSH_GWA_ADCMOFFSET',
    'INRSH_FWA_ADCMOFFSET',
    'INRSH_OA_VREFOFF',
    'INRSH_RMA_ADCMOFFSET'
]

# List of anomalys to be displayed on a certain page
list_wheel =[
    'INRSI_FWA_MECH_POS',
    'INRSI_C_FWA_POSITION',
    'INRSI_GWA_MECH_POS',
    'INRSI_C_GWA_X_POSITION',
    'INRSI_GWA_MECH_POS',
    'INRSI_C_GWA_Y_POSITION',
]

# List of anomalys to be displayed on a certain page
list_caa = [
    'INRSH_LAMP_SEL',
    'INRSI_C_CAA_CURRENT',
    'INRSI_C_CAA_VOLTAGE',
    'INRSH_CAA_VREFOFF',
    'INRSH_CAA_VREF',
]

# List of anomalys to be displayed on a certain page
list_fpe_fpa = [
    'IGDP_NRSD_ALG_A1_VDDA',
    'IGDP_NRSD_ALG_A1GND4VDA',
    'IGDP_NRSD_ALG_A1GND5VRF',
    'INRSD_ALG_A1_VDD3P3',
    'INRSD_ALG_A1_VDD',
    'INRSD_ALG_A1_REF',
    'INRSD_A1_DSUB_V',
    'INRSD_A1_VRESET_V',
    'INRSD_A1_CELLDRN_V',
    'INRSD_A1_DRAIN_V',
    'INRSD_A1_VBIASGATE_V',
    'INRSD_A1_VBIASPWR_V',
    'IGDP_NRSD_ALG_A1_VDD_C',
    'IGDP_NRSD_ALG_A1VDAP12C',
    'IGDP_NRSD_ALG_A1VDAN12C',
    'INRSD_A1_VDDA_I',
    'IGDP_NRSD_ALG_A2_VDDA',
    'IGDP_NRSD_ALG_A2GND4VDA',
    'IGDP_NRSD_ALG_A2GND5VRF',
    'INRSD_ALG_A2_VDD3P3',
    'INRSD_ALG_A2_VDD',
    'INRSD_ALG_A2_REF',
    'INRSD_A2_DSUB_V',
    'INRSD_A2_VRESET_V',
    'INRSD_A2_CELLDRN_V',
    'INRSD_A2_DRAIN_V',
    'INRSD_A2_VBIASGATE_V',
    'INRSD_A2_VBIASPWR_V',
    'IGDP_NRSD_ALG_A2_VDD_C',
    'IGDP_NRSD_ALG_A2VDAP12C',
    'IGDP_NRSD_ALG_A2VDAN12C',
    'INRSD_A2_VDDA_I',
]

# List of anomalys to be displayed on a certain page
list_msa_mce = [
    'INRSM_MCE_AIC_1R5_V',
    'INRSM_MCE_AIC_3R3_V',
    'INRSM_MCE_AIC_5_V',
    'INRSM_MCE_AIC_P12_V',
    'INRSM_MCE_AIC_N12_V',
    'INRSM_MCE_AIC_3R3_I',
    'INRSM_MCE_AIC_5_I',
    'INRSM_MCE_AIC_P12_I',
    'INRSM_MCE_AIC_N12_I',
    'INRSM_MCE_MDAC_1R5_V',
    'INRSM_MCE_MDAC_3R3_V',
    'INRSM_MCE_MDAC_5_V',
    'INRSM_MCE_MDAC_P12_V',
    'INRSM_MCE_MDAC_N12_V',
    'INRSM_MCE_MDAC_3R3_I',
    'INRSM_MCE_MDAC_5_I',
    'INRSM_MCE_MDAC_P12_I',
    'INRSM_MCE_MDAC_N12_I',
    'INRSM_MSA_Q1_365VDD',
    'INRSM_MSA_Q2_365VDD',
    'INRSM_MSA_Q3_365VDD',
    'INRSM_MSA_Q4_365VDD',
    'INRSM_MSA_Q1_365VPP',
    'INRSM_MSA_Q2_365VPP',
    'INRSM_MSA_Q3_365VPP',
    'INRSM_MSA_Q4_365VPP',
    'INRSM_MSA_Q1_171VPP',
    'INRSM_MSA_Q2_171VPP',
    'INRSM_MSA_Q3_171VPP',
    'INRSM_MSA_Q4_171VPP',
    'IGDPM_MSA_Q1_365IDD',
    'IGDPM_MSA_Q2_365IDD',
    'IGDPM_MSA_Q3_365IDD',
    'IGDPM_MSA_Q4_365IDD',
    'IGDPM_MSA_Q1_365IPP',
    'IGDPM_MSA_Q2_365IPP',
    'IGDPM_MSA_Q3_365IPP',
    'IGDPM_MSA_Q4_365IPP',
    'IGDPM_MSA_Q1_171RTN',
    'IGDPM_MSA_Q2_171RTN',
    'IGDPM_MSA_Q3_171RTN',
    'IGDPM_MSA_Q4_171RTN',
]

# List of anomalys to be displayed on a certain page
list_power = [
    'GP_ZPSVOLT',
    'SE_ZINRSICEA',
    'SE_ZINRSICEB',
    'INRSH_HK_P15V',
    'INRSH_HK_N15V',
    'INRSH_HK_VMOTOR',
    'INRSH_HK_P5V',
    'INRSH_HK_2P5V',
    'INRSH_HK_ADCTGAIN',
    'INRSH_HK_ADCTOFFSET',
    'INRSH_OA_VREFOFF',
    'INRSH_OA_VREF',
    'GP_ZPSVOLT',
    'SE_ZINRSMCEA',
    'SE_ZINRSMCEB',
    'GP_ZPSVOLT',
    'SE_ZINRSFPEA',
    'SE_ZINRSFPEB',
    'INRSD_ALG_ACC_P12C',
    'INRSD_ALG_ACC_N12C',
    'INRSD_ALG_ACC_3D3_1D5_C',
    'INRSD_ALG_CHASSIS',
]

# List of anomalys to be displayed on a certain page
list_temperature = [
    'SI_GZCTS75A',
    'SI_GZCTS75B',
    'SI_GZCTS68A',
    'SI_GZCTS68B',
    'SI_GZCTS81A',
    'SI_GZCTS81B',
    'SI_GZCTS80A',
    'SI_GZCTS80B',
    'SI_GZCTS76A',
    'SI_GZCTS76B',
    'SI_GZCTS79A',
    'SI_GZCTS79B',
    'SI_GZCTS77A',
    'SI_GZCTS77B',
    'SI_GZCTS78A',
    'SI_GZCTS78B',
    'SI_GZCTS69A',
    'SI_GZCTS69B',
    'IGDP_NRSD_ALG_TEMP',
    'INRSH_HK_TEMP1',
    'INRSH_HK_TEMP2',
    'IGDP_NRSI_C_CAM_TEMP',
    'IGDP_NRSI_C_COL_TEMP',
    'IGDP_NRSI_C_COM1_TEMP',
    'IGDP_NRSI_C_FOR_TEMP',
    'IGDP_NRSI_C_IFU_TEMP',
    'IGDP_NRSI_C_BP1_TEMP',
    'IGDP_NRSI_C_BP2_TEMP',
    'IGDP_NRSI_C_BP3_TEMP',
    'IGDP_NRSI_C_BP4_TEMP',
    'IGDP_NRSI_C_RMA_TEMP',
    'IGDP_NRSI_C_CAAL1_TEMP',
    'IGDP_NRSI_C_CAAL2_TEMP',
    'IGDP_NRSI_C_CAAL3_TEMP',
    'IGDP_NRSI_C_CAAL4_TEMP',
    'IGDP_NRSI_C_FWA_TEMP',
    'IGDP_NRSI_C_GWA_TEMP',
    'INRSM_MCE_PCA_TMP1',
    'INRSM_MCE_PCA_TMP2',
    'INRSM_MCE_AIC_TMP_FPGA',
    'INRSM_MCE_AIC_TMP_ADC',
    'INRSM_MCE_AIC_TMP_VREG',
    'INRSM_MCE_MDAC_TMP_FPGA',
    'INRSM_MCE_MDAC_TMP_OSC',
    'INRSM_MCE_MDAC_TMP_BRD',
    'INRSM_MCE_MDAC_TMP_PHA',
    'INRSM_MCE_MDAC_TMP_PHB',
    'INRSM_Q1_TMP_A',
    'INRSM_Q2_TMP_A',
    'INRSM_Q3_TMP_A',
    'INRSM_Q4_TMP_A',
    'INRSM_MECH_MTR_TMP_A',
    'INRSM_LL_MTR_TMP_A',
    'INRSM_MSA_TMP_A',
    'IGDP_NRSD_ALG_FPA_TEMP',
    'IGDP_NRSD_ALG_A1_TEMP',
    'IGDP_NRSD_ALG_A2_TEMP',
    'SI_GZCTS74A',
    'SI_GZCTS74B',
    'SI_GZCTS67A',
    'SI_GZCTS67B',
]

